name: GitHub repo fork sync

on:
  schedule:
    - cron: "0 0 * * MON"
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: GeoNet/yq@bbe305500687a5fe8498d74883c17f0f06431ac4
      - id: set
        run: |
          echo "matrix=$(jq '.repos' -r -c <<< "$(yq e . -o json config/fork-sync.yaml)")" >> $GITHUB_OUTPUT
      - name: check output
        run: |
          jq . <<< '${{ steps.prepare.outputs.matrix }}'

  build:
    needs: prepare
    strategy:
      matrix:
        include: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    uses: GeoNet/Actions/.github/workflows/reusable-github-repo-fork-sync.yml@main
    with:
      name: ${{ fromJSON(toJSON(matrix)).name }}
