name: presubmit ensure reusable workflow is documented
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  ensure-reusable-workflow-is-documented:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - run: |
          FAILURES=false
          for WORKFLOW in $(find .github/workflows -name 'reusable*' | xargs); do
            if ! grep -q "$WORKFLOW" README.md; then
              echo "Not found in README: $WORKFLOW"
              FAILURES=true
            fi
          done
          if [ "$FAILURES" = true ]; then
            exit 1
          fi
