name: require actions run from GeoNet org
on:
  pull_request: {}
  workflow_dispatch: {}
env:
  REQUIRED_STRING_GENERIC: "startsWith(github.repository, 'GeoNet/') == false" # use the steps field and exit 1
  REQUIRED_STRING_APPS: "startsWith(github.repository, 'GeoNet/') != false" # use existing if statements for the chained reuse of workflows, since there's no steps field
jobs:
  require-actions-run-from-GeoNet-org:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - run: |
          FAILURES=false
          for WORKFLOW in $(find .github/workflows -name 'reusable*' | xargs); do
            if ! ( grep -q "$REQUIRED_STRING_GENERIC" "$WORKFLOW" \
              || ( echo "$WORKFLOW" | grep -q apps && grep -q "$REQUIRED_STRING_APPS" "$WORKFLOW" ) ); then
              echo "Reusable workflow must be restricted to only run from GeoNet org: $WORKFLOW"
              FAILURES=true
            fi
          done
          if [ "$FAILURES" = true ]; then
            exit 1
          fi
