name: presubmit ensure reusable workflow is documented
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  ensure-reusable-workflow-is-documented:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: |
          FAILURES=false
          for WORKFLOW in $(find .github/workflows -name 'reusable*' | xargs); do
            if ! grep -q "$WORKFLOW" README.md; then
              echo "Not found in README: $WORKFLOW"
              FAILURES=true
            fi
          done
          if [ "$FAILURES" = true ]; then
            exit 1
          fi
