name: check actions exist
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  check-actions-exist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: run check-actions-exist.sh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./hack/check-actions-exist.sh
