name: check actions exist
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  check-actions-exist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: run check-actions-exist.sh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./hack/check-actions-exist.sh
