name: reusable-presubmit-github-actions-action-validator
on:
  workflow_call:
    inputs:
      actionPaths:
        type: string
        required: true
        default: action.yml
        description: |
          the path to a GitHub action.yml files
jobs:
  validate-github-actions:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ startsWith(github.repository, 'GeoNet/') == false }}
        name: require GeoNet org
        run: |
          exit 1
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: stable
          check-latest: true
      - name: download schema
        run: |
          curl -sSL https://json.schemastore.org/github-action.json -o /tmp/github-action-schema.json
      - name: validate actions
        env:
          VERSION_JSONSCHEMA: df30d55b699bcc4c63d43a131017799715c1ae1a # v5.3.0
          ACTIONS: ${{ inputs.actionPaths }}
        run: |
          FAILURES=false
          for ACTION in "${ACTIONS[@]}"; do
            echo "validating '$ACTION'"
            if ! go run "github.com/santhosh-tekuri/jsonschema/cmd/jv@$VERSION_JSONSCHEMA" -- /tmp/github-action-schema.json "$ACTION"; then
              FAILURES=true
            fi
          done
          if [ "$FAILURES" = true ]; then
            exit 1
          fi
