name: reusable govulncheck
on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: '.'
        description: |
          the working directory of the application
jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ startsWith(github.repository, 'GeoNet/') == false }}
        name: require GeoNet org
        run: |
          exit 1
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: ${{ inputs.working-directory }}/go.mod
          cache-dependency-path: ${{ inputs.working-directory }}/go.sum
          check-latest: true
      - name: govulncheck
        id: govulncheck
        env:
          WORK_DIR: ${{ inputs.working-directory }}
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck -C $WORK_DIR ./...
