name: reusable go test
env:
  VERSION_CRANE: v0.16.1
on:
  workflow_call:
    inputs:
      aws-role-arn-to-assume:
        type: string
        required: false
        description: |
          role to use to upload test results to s3 bucket,
          see copy-to-s3 action for more detail.
      s3-bucket:
        type: string
        required: false
        description: |
          the AWS S3 bucket name to upload test results to.
      setup:
        required: false
        type: string
        description: |
          shell commands to setup the test environment
      extraArgs:
        required: false
        type: string
        description: |
          extra args to pass `go test`
      go-version:
        default: oldstable
        type: string
        description: |
          Go version to use, see `actions/setup-go` for more information.
      registry:
        required: false
        type: string
        description: |
          ECR registry
      aws-region:
        type: string
        required: false
        description: |
          the AWS region to use; e.g ap-southeast-2
      aws-role-arn-to-assume-ecr:
        type: string
        required: false
        description: |
          an AWS role ARN to assume.
          e.g: arn:aws:iam::ACCOUNT_ID:role/github-actions-ROLE_NAME
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ startsWith(github.repository, 'GeoNet/') == false }}
        name: require GeoNet org
        run: |
          exit 1
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ inputs.go-version }}
          cache-dependency-path: go.sum
          check-latest: true
      - uses: GeoNet/setup-crane@00c9e93efa4e1138c9a7a5c594acd6c75a2fbf0c # main
        with:
          version: ${{ env.VERSION_CRANE }}
      - name: Configure AWS Credentials
        if: ${{ inputs.aws-region != '' && inputs.aws-role-arn-to-assume-ecr != '' }}
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.aws-role-arn-to-assume-ecr }}
      - name: login to ECR
        if: ${{ inputs.aws-region != '' &&  inputs.registry != '' }}
        run: |
          aws ecr get-login-password --region ${{ inputs.aws-region }} | crane auth login ${{ inputs.registry }} -u AWS --password-stdin
      - name: setup
        run: |
          eval '${{ inputs.setup }}'
      - name: test
        id: test
        env:
          EXTRA_ARGS: ${{ inputs.extraArgs }}
        run: |
          go test $EXTRA_ARGS -v -coverprofile /tmp/coverage.out -cover ./...
      - name: create coverage html
        id: coverage-html
        run: |
          go tool cover -html=/tmp/coverage.out -o /tmp/coverage.html
      - name: Upload test log to GitHub Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: test-results
          path: |
            /tmp/coverage.out
            /tmp/coverage.html
          if-no-files-found: error
          retention-days: 1
          overwrite: true
      - name: Upload test log to S3
        if: ${{ inputs.aws-role-arn-to-assume && inputs.s3-bucket }}
        uses: GeoNet/Actions/.github/actions/copy-to-s3@main
        with:
          aws-role-arn-to-assume: ${{ inputs.aws-role-arn-to-assume }}
          artifact-name: test-results
          artifact-path: ./coverage
          s3-bucket-uri: s3://${{inputs.s3-bucket}}/test-coverage-results/${{github.repository}}/go/
