name: Reusable GitHub repo fork sync
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
        default: ''
        description: |
          an org and repo string formatted as 'Org/Repo' like 'GeoNet/setup-ko'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - id: sync
        if: ${{ inputs.name != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || github.token }}
        run: |
          gh repo sync --force ${{ inputs.name }}
