name: reusable gofmt
on:
  workflow_call: {}
jobs:
  go-fmt:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ startsWith(github.repository, 'GeoNet/') == false }}
        name: require GeoNet org
        run: |
          exit 1
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
          check-latest: true
      - name: gofmt
        id: gofmt
        run: find . -name "*.go" | grep -E -v vendor | xargs gofmt -s -l -d -e
