name: reusable eslint
on:
  workflow_call:
    inputs:
      paths:
        required: true
        type: string
        description: |
          A list of root directory/s to where a package.json and eslint
          configuration file (eslint.config.mjs) exist.
          e.g.: my/root/one my/cool/root/two
      node-version:
        required: false
        type: string
        default: "21.x"
        description: |
          The version of Node to use when installing node modules and
          running eslint.
          See https://github.com/actions/setup-node?tab=readme-ov-file#supported-version-syntax
          for syntax.
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ startsWith(github.repository, 'GeoNet/') == false }}
        name: require GeoNet org
        run: |
          exit 1
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install Node modules
        id: install-node-modules
        env:
          PATHS: ${{ inputs.paths }}
        run: |
          for path in $PATHS; do
            npm install-clean --prefix $path
          done
      - name: Run ESLint
        id: eslint
        env:
          PATHS: ${{ inputs.paths }}
        run: |
          for path in $PATHS; do
            ESLINT_USE_FLAT_CONFIG=true $path/node_modules/.bin/eslint -c $path/eslint.config.mjs $path
          done
