name: reusable gofmt
on:
  workflow_call: {}
jobs:
  go-fmt:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ startsWith(github.repository, 'GeoNet/') == false }}
        run: |
          exit 1
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
          check-latest: true
      - name: gofmt
        id: gofmt
        run: find . -name "*.go" | grep -E -v vendor | xargs gofmt -s -l -d -e
