name: reusable go test
on:
  workflow_call:
    inputs:
      setup:
        required: false
        type: string
        description: |
          shell commands to setup the test environment
      extraArgs:
        required: false
        type: string
        description: |
          extra args to pass `go test`
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ startsWith(github.repository, 'GeoNet/') == false }}
        name: require GeoNet org
        run: |
          exit 1
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
          check-latest: true
      - name: setup
        run: |
          eval '${{ inputs.setup }}'
      - name: test
        id: test
        env:
          EXTRA_ARGS: ${{ inputs.extraArgs }}
        run: |
          go test $EXTRA_ARGS -v -coverprofile /tmp/coverage.out -cover ./...
      - name: create coverage html
        id: coverage-html
        run: |
          go tool cover -html=/tmp/coverage.out -o /tmp/coverage.html
      - name: Upload test log
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        if: always()
        with:
          name: test-results
          path: |
            /tmp/coverage.out
            /tmp/coverage.html
          if-no-files-found: error
          retention-days: 1
