name: reusable gofmt
on:
  workflow_call:
    inputs:
      go-version:
        default: oldstable
        type: string
        description: |
          Go version to use, see `actions/setup-go` for more information.

jobs:
  go-fmt:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ startsWith(github.repository, 'GeoNet/') == false }}
        name: require GeoNet org
        run: |
          exit 1
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ inputs.go-version }}
          cache-dependency-path: go.sum
          check-latest: true
      - name: gofmt
        id: gofmt
        run: find . -name "*.go" | grep -E -v vendor | xargs gofmt -s -l -d -e
