name: reusable golangci lint
on:
  workflow_call:
    inputs:
      config:
        type: string
        required: false
        description: |
          a .golangci.yml configuration file.
          Warning: setting this field will override an existing config
      setup:
        required: false
        type: string
        description: |
          shell commands to setup the test environment
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - if: ${{ startsWith(github.repository, 'GeoNet/') == false }}
        name: require GeoNet org
        run: |
          exit 1
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
          check-latest: true
      - name: write .golangci.yml
        if: ${{ inputs.config }}
        run: |
          echo "Using config:"
          echo '${{ inputs.config }}' | tee .golangci.yml
      - name: setup
        run: |
          eval '${{ inputs.setup }}'
      - name: golangci-lint
        uses: GeoNet/golangci-lint-action@1b9b0798df716be5ff7cebc26795b000939a4b41 # master
        with:
          version: v1.63.4
          args: --timeout 30m -E gosec
