name: reusable-presubmit-github-actions-workflow-validator
on:
  workflow_call: {}
jobs:
  validate-github-actions:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ startsWith(github.repository, 'GeoNet/') == false }}
        name: require GeoNet org
        run: |
          exit 1
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: stable
          check-latest: true
      - name: download schema
        run: |
          curl -sSL https://json.schemastore.org/github-workflow.json -o /tmp/github-workflow-schema.json
      - name: validate actions
        env:
          VERSION_JSONSCHEMA: df30d55b699bcc4c63d43a131017799715c1ae1a # v5.3.0
        run: |
          FAILURES=false
          for WORKFLOW in $(find .github/workflows -type f | sort); do
            echo "validating '$WORKFLOW'"
            go run "github.com/santhosh-tekuri/jsonschema/cmd/jv@$VERSION_JSONSCHEMA" -- /tmp/github-workflow-schema.json "$WORKFLOW" || FAILURES=true
          done
          if [ "$FAILURES" = true ]; then
            exit 1
          fi
