name: reusable presubmit README table of contents
on:
  workflow_call:
    inputs:
      readmePath:
        type: string
        default: README.md
        description: |
          the path to the README.md
env:
  VERSION_MDTOC: 7993442ed6a3dd528d34eb36b36cb085c17e17b0
jobs:
  presubmit-readme-toc:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ startsWith(github.repository, 'GeoNet/') == false }}
        name: require GeoNet org
        run: |
          exit 1
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: stable
          check-latest: true
      - env:
          READMEPATH: ${{ inputs.readmePath }}
        name: generate table of contents
        run: |
          go run sigs.k8s.io/mdtoc@$VERSION_MDTOC --inplace $READMEPATH
      - id: changes
        name: determine changes
        env:
          READMEPATH: ${{ inputs.readmePath }}
        run: |
          if git diff --name-only --diff-filter=ACMRT | grep $READMEPATH; then
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
      - if: ${{ steps.changes.outputs.changes == 'true' }}
        name: changes are detected
        env:
          READMEPATH: ${{ inputs.readmePath }}
        run: |
          echo "changes detected" >/dev/stderr
          echo "Please run 'go run sigs.k8s.io/mdtoc@latest --inplace $READMEPATH' and commit again."
          exit 1
