# helpful wiki
# link: https://www.shellcheck.net/wiki/

name: reusable bash shellcheck
on:
  workflow_call: {}
jobs:
  bash-shellcheck:
    name: bash-shellcheck
    runs-on: ubuntu-latest
    steps:
      - if: ${{ startsWith(github.repository, 'GeoNet/') == false }}
        run: |
          exit 1
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - id: run-info
        name: collect job run info
        run: |
          all_shell_scripts=()
          while IFS=$'\n' read -r script; do
            git check-ignore -q "$script" || all_shell_scripts+=("$script")
          done < <(grep -irl '#!.*sh' . --exclude-dir={_\*,.git\*,vendor\*})
          echo "scripts=${all_shell_scripts[@]}" >> $GITHUB_OUTPUT
      - id: shellcheck
        if: ${{ steps.run-info.outputs.scripts }}
        uses: docker://docker.io/koalaman/shellcheck-alpine:v0.9.0
        with:
          entrypoint: shellcheck
          args: --external-sources --exclude=2230 --color=auto ${{ steps.run-info.outputs.scripts }}
