name: reusable go test
on:
  workflow_call:
    inputs:
      aws-role-arn-to-assume:
        type: string
        required: false
        description: |
          role to use to upload test results to s3 bucket,
          see reusable-copy-to-s3 workflow for more detail.
      s3-bucket:
        type: string
        required: false
        description: |
          the AWS S3 bucket name to upload test results to.
      setup:
        required: false
        type: string
        description: |
          shell commands to setup the test environment
      extraArgs:
        required: false
        type: string
        description: |
          extra args to pass `go test`
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ startsWith(github.repository, 'GeoNet/') == false }}
        name: require GeoNet org
        run: |
          exit 1
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
          check-latest: true
      - name: setup
        run: |
          eval '${{ inputs.setup }}'
      - name: test
        id: test
        env:
          EXTRA_ARGS: ${{ inputs.extraArgs }}
        run: |
          go test $EXTRA_ARGS -v -coverprofile /tmp/coverage.out -cover ./...
      - name: create coverage html
        id: coverage-html
        run: |
          go tool cover -html=/tmp/coverage.out -o /tmp/coverage.html
      - name: Upload test log
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        if: always()
        with:
          name: test-results
          path: |
            /tmp/coverage.out
            /tmp/coverage.html
          if-no-files-found: error
          retention-days: 1
          overwrite: true
      - name: Upload test log to S3
        uses: GeoNet/Actions/.github/actions/copy-to-s3@caS3
        if: ${{ inputs.aws-role-arn-to-assume && inputs.s3-bucket }}
        with:
          aws-role-arn-to-assume: ${{ inputs.aws-role-arn-to-assume }}
          artifact-name: test-results
          artifact-path: ./coverage
          s3-bucket-uri: s3://${{inputs.s3-bucket}}/test-coverage-results/${{github.repository}}/go/
    

