name: reusable-dockerfile-lint
on:
  workflow_call:
    inputs:
      dockerfiles:
        type: string
        required: false
        description: |
          the selected Dockerfiles to lint
jobs:
  dockerfile-lint:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ startsWith(github.repository, 'GeoNet/') == false }}
        name: require GeoNet org
        run: |
          exit 1
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - id: run-info
        name: discover Dockerfiles and Containerfiles
        env:
          INPUTS: ${{ inputs.dockerfiles }}
        run: |
          DOCKERFILES="$(find . -name '*Dockerfile*' -or -name '*Containerfile' | xargs | tr ' ' ',')"
          if [ -n "$INPUTS" ]; then
            DOCKERFILES="$INPUTS"
          fi
          echo "dockerfiles=$DOCKERFILES" >> $GITHUB_OUTPUT
      - name: lint
        env:
          DOCKERFILES: ${{ steps.run-info.outputs.dockerfiles }}
        run: |
          echo "linting: ${DOCKERFILES//,/ }"
          docker run --rm -v "$PWD:$PWD" --workdir "$PWD" ghcr.io/geonet/base-images/hadolint/hadolint:v2.12.0-alpine hadolint ${DOCKERFILES//,/ }
