name: reusable golangci lint
on:
  workflow_call:
    inputs:
      config:
        type: string
        required: false
        description: |
          a .golangci.yml configuration file.
          Warning: setting this field will override an existing config
      setup:
        required: false
        type: string
        description: |
          shell commands to setup the test environment
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - if: ${{ startsWith(github.repository, 'GeoNet/') == false }}
        run: |
          exit 1
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
          check-latest: true
      - name: write .golangci.yml
        if: ${{ inputs.config }}
        run: |
          echo "Using config:"
          echo '${{ inputs.config }}' | tee .golangci.yml
      - name: setup
        run: |
          eval '${{ inputs.setup }}'
      - name: golangci-lint
        uses: GeoNet/golangci-lint-action@4cb96975783006316142911dac808e71dd8b0b40 # master
        with:
          version: v1.52.2
          args: --timeout 30m -E gosec
