name: sync actions forks
on:
  push:
    branches: sync-forks
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch: {}
jobs:
  prepare:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.repository, 'mountainmoss/') == false }}
    steps:
    - name: require GeoNet org
      run: |
        exit 1
  sync-forks:
    env:
      FORKS: (mountainmoss/setup-ko mountainmoss/setup-crane mountainmoss/chainguard-dev-actions mountainmoss/golangci-lint-action mountainmoss/conform-actions mountainmoss/chainguard-images-actions mountainmoss/terraform-linters-setup-tflint)
    runs-on: ubuntu-latest
    steps:
      - name: configure system
        run: |
          gh auth login --with-token < <(echo ${{ secrets.GITHUB_TOKEN }})
          gh auth status
      - name: determine changes
        id: determine-changes
        run: |
          for FORK in "${!FORKS[@]}";
          do
            BRANCH=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${FORKS[$FORK]} | jq -rc .default_branch)

            gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${FORKS[$FORK]}/merge-upstream \
            -f branch="${BRANCH}"
          done
